### Import libraries

In [ ]:
import numpy as np                                          # numerical computing and array manipulation

from tensorflow.keras.preprocessing.text import one_hot     # converts words into integer indices
from tensorflow.keras.layers import Embedding               # converts word indices into dense vectors
from tensorflow.keras.models import Sequential              # builds a model with sequential layers
from tensorflow.keras.utils import pad_sequences            # makes all sequences the same length

In [2]:
samples = ['the glass of milk','the glass of juice','the cup of tea','I am a good by',
           'I am a good developer','understand the meaning of word','your videos are good']

In [3]:
# Define vocabulary size
voc_size = 10000

In [4]:
samples

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good by',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

### One-Hot Representation

**NOTE**: `one_hot(input_test, n, filters, lower, split, analyzer)`

In [5]:
# One hot representation for every word
oh_repr = [one_hot(word, voc_size) for word in samples]
oh_repr

[[7816, 8347, 8249, 4533],
 [7816, 8347, 8249, 2069],
 [7816, 4355, 8249, 8353],
 [3040, 4764, 2112, 169, 1436],
 [3040, 4764, 2112, 169, 5742],
 [1371, 7816, 4438, 8249, 7172],
 [3792, 6953, 641, 169]]

**Representation**  
$\Rightarrow$ [5562, 9855, 4561, 4996] are the indices of each word vector  
- `the` = 5562  
- `glass` = 9855  
- `of` = 4561  
- `mile` = 4996 

> After dimensionality reduction using PCA, some vectors are very near to each other after plotting using **cosine similarity**.

**NOTE:**  
- Since the length of the senentes are different, maximum length are needed to be set the length before training.
- We set the maximum length of the words as `8`, but the real maximum length is `5`. We need to set the extra 3 values as 0 before or after the real words using `pad_sequences()`.

In [ ]:
# Word embedding representation
max_length = 8
embedded_docs = pad_sequences(pad_sequences=oh_repr, padding='pre', maxlen=max_length)   # Pre insertion (USED)
print(embedded_docs)
print(pad_sequences(pad_sequences=oh_repr, padding='post', maxlen=max_length))           # Post insertion

[[   0    0    0    0 7816 8347 8249 4533]
 [   0    0    0    0 7816 8347 8249 2069]
 [   0    0    0    0 7816 4355 8249 8353]
 [   0    0    0 3040 4764 2112  169 1436]
 [   0    0    0 3040 4764 2112  169 5742]
 [   0    0    0 1371 7816 4438 8249 7172]
 [   0    0    0    0 3792 6953  641  169]]
[[7816 8347 8249 4533    0    0    0    0]
 [7816 8347 8249 2069    0    0    0    0]
 [7816 4355 8249 8353    0    0    0    0]
 [3040 4764 2112  169 1436    0    0    0]
 [3040 4764 2112  169 5742    0    0    0]
 [1371 7816 4438 8249 7172    0    0    0]
 [3792 6953  641  169    0    0    0    0]]


In [7]:
# Feature representation (Embedding model)
dim = 10

model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(max_length, )))
model.compile(optimizer='adam', loss='mse', metrics=['mse'])
model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.predict(embedded_docs)
# NOTE: Every words represent 10 dimensions.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[ 0.00995791,  0.00274764,  0.03434844, -0.02434318,
         -0.02538081,  0.01435235,  0.006979  ,  0.00674386,
          0.02408253,  0.015855  ],
        [ 0.00995791,  0.00274764,  0.03434844, -0.02434318,
         -0.02538081,  0.01435235,  0.006979  ,  0.00674386,
          0.02408253,  0.015855  ],
        [ 0.00995791,  0.00274764,  0.03434844, -0.02434318,
         -0.02538081,  0.01435235,  0.006979  ,  0.00674386,
          0.02408253,  0.015855  ],
        [ 0.00995791,  0.00274764,  0.03434844, -0.02434318,
         -0.02538081,  0.01435235,  0.006979  ,  0.00674386,
          0.02408253,  0.015855  ],
        [ 0.03110665, -0.03807173,  0.01725303,  0.01830618,
          0.04899453,  0.03418375,  0.01822403,  0.00205178,
         -0.03812956,  0.00953029],
        [-0.02151607,  0.03456291,  0.02952248, -0.04255956,
         -0.02516872,  0.00060103, -0.01448635,  0.04845927,
          0.04192228, -0.01322799],
        [-0.04577601, -0.03625328,  0.01620959, -0.0